### ISSUE TITLE
sliders

### ISSUE THREAD

**Issue by Nikhil-2002** [Nikhil-2002/development_Hactoberfest23#3]

**Comment by Piyush-Gambhir** [comment]
Could you specify what exactly I will have to make in this. Also I can work on this issue after that.

**Comment by Nikhil-2002** [comment]
add different types of sliders like box slider,image slider,card slider,etc using HTML, CSS,js,bootstrap

**Comment by Piyush-Gambhir** [comment]
Please assign this issue to me.

**Comment by pawan8120** [comment]
can you please assign this issue to me

**Comment by Myworld21** [comment]
I want to work on this interesting Project. Can you please assign it to me.

**Comment by soumili202** [comment]
Can you please assign this issue to me?

**Comment by Pritee-gupta-jpg** [comment]
Please assign this to me
