### ISSUE TITLE
Additional out line Visible on Add to cart Button 

### ISSUE THREAD

**Issue by rakzool** [Nikhil-2002/development_Hactoberfest23#37]
additional outline Visible on Add to cardt button for Main React App in the repo

**Comment by rakzool** [comment]
@Nikhil-2002  pls assign this issue to me also pls add labels for Hactoberfest 2023 , will issuer a PR on new branch

**Comment by AtharvEkavire** [comment]
If you want to add additional information or an outline to a "Add to Cart" button on a web page, you can achieve this using HTML and CSS

Assign ME

**Comment by Kedarnath-Rothe** [comment]
Pleas assign me this issue

**Comment by ezhillragesh** [comment]
Hello there @Nikhil-2002 ,

I hope you're doing well. I've been following issue #37, "Additional outline visible on Add to cart button," and I'd like to contribute to its resolution.

Is it possible to assign this issue to me? I believe I can help in addressing the problem and working towards a solution. Looking forward to your response.

Best regards,
Ezhill Ragesh

**Comment by sp-gits** [comment]
I am very familiar with this issue , have done it before . You can assign this issue to me

**Comment by ezhillragesh** [comment]
I created a PR for this issue #73

**Comment by rakzool** [comment]
the issue was aready resolved and the code had been mergerd , closing it now
