### ISSUE TITLE
mini websites

### ISSUE THREAD

**Issue by Nikhil-2002** [Nikhil-2002/development_Hactoberfest23#5]

**Comment by subhro1530** [comment]
Giving you a PR for a mini-app right now.. Please be specific about what kind of apps you wish for so that i can work on them as well! Thank you.. KIndly assign me this..

**Comment by Nikhil-2002** [comment]
you have to push mini websites not apps

**Comment by JenilGajjar20** [comment]
Hey, @Nikhil-2002. Can you assign me this task under **hacktoberfest**. I have few mini-websites using Vue.js.

**Comment by gamandeepsingh** [comment]
please assign for the same ..... i have made one Car-Rental project on reactJS...which is working well

**Comment by Swapnil-DevGeek** [comment]
Hey @Nikhil-2002 can you please assign this to me under **hactoberfest** . I have some react js mini projects

**Comment by vilasrhegde** [comment]
Hey @Nikhil-2002 Can you assign me? I will add community based application using Django (Similar to StackOverflow)

**Comment by ShivanshDengla** [comment]
Hey @Nikhil-2002 can you please assign me this Issue? I'm going to make some pull requests for Hacktoberfest

**Comment by Madanraj0519** [comment]
Hey @JenilGajjar20 Could you assign me to this issue?

**Comment by alinasoy** [comment]
Hey @Nikhil-2002 can you please assign this to me under hactoberfest . I have a mini projects related to game using reactjs.

**Comment by Kedarnath-Rothe** [comment]
please assign to me

**Comment by ezhillragesh** [comment]
Hey @Nikhil-2002,

I'm interested in working on this issue. I have experience with mini-projects developed using React.js, and I'm excited to contribute to this project. Could you please assign this issue to me?

Looking forward to getting started!

Best regards,
Ezhill Ragesh

**Comment by ayushranjan025** [comment]
added guess my number game and made a PR with #77 
please merge it
